services:
  database:
    image: mongo:latest
    container_name: database
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      DB_URI: ${DB_URI}
      PORT: ${BACKEND_PORT}
    depends_on:
      - database
    networks:
      - net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      PORT: ${FRONTEND_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
    depends_on:
      - backend
    networks:
      - net

volumes:
  data:

networks:
  net:
    driver: bridge