services:
  database:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    networks:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      PORT: ${BACKEND_PORT}
      DB_URI: mongodb://${DB_USER}:${DB_PASS}@database:27017
    depends_on:
      - database
    networks:
      - backend
      - frontend

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      PORT: ${FRONTEND_PORT}
      API_URI: http://backend:${BACKEND_PORT}
    depends_on:
      - backend
    networks:
      - frontend

volumes:
  data:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge